version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7.36
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: vasa
      MYSQL_PASSWORD: vasa
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  adminer:
    image: adminer
    ports:
      - 8090:8080