version: '3.9'
services:
  backend:
    build: .
    ports:
      - 7000:7000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    platform: linux/x86_64
    image: mysql:5.7.36
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: vasa
      MYSQL_PASSWORD: vasa
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  adminer:
    image: adminer
    ports:
      - 7090:8080